name: main
on:
  push: # ci work when pushing master branch
    branches:
      - master
  pull_request: # ci work when creating a PR to master branch
    branches:
      - master
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        python-version: [3.6, 3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-jax.txt
        pip install -r requirements.txt
        pip install -r requirements-tests.txt
        pip install -r requirements-docs.txt
    - name: Build jaxchem
      run: |
        python setup.py install
    - name: Lint with flake8
      run: |
        flake8 . --count --show-source --statistics
    - name: Type check
      run: |
        mypy --ignore-missing-imports jaxchem examples/*
    - name: Test with pytest
      run: |
        pytest -v --cov=jaxchem
    - name: Build documents
      run: |
          cd docs && make html
